### ISSUE TITLE
Identify components from wireframes

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#1]
Here are some components we identified in a component/pattern inventory exercise on 2/9/15:
We should go through to label and name each of these (along with their variations) for clarity.

![slack for ios upload](https://cloud.githubusercontent.com/assets/1198350/12958960/3c829d30-d002-11e5-8244-5b587f293be7.jpg)

**Comment by alxmrtnz** [comment]
Hey @heyitsolivia, I've put together an initial sheet of components that are to be used across our template pages. I left out things like the content block, news components, contact form, and other elements that are unique to specific pages.

I also made note of components that may have some variation in terms of showing/hiding parts or changing alignment of content.

Let me know what you think.

![component sheet](https://cloud.githubusercontent.com/assets/1167326/13085608/0cec81a8-d4ad-11e5-9998-32353f599316.jpg)

**Comment by heyitsolivia** [comment]
@alxmrtnz This is looking really good so far, and the variations for each block is also helpful.

Let's also add in all the other components that we'll be using like the content block and other unique blocks— that'll allow us to see how much we'll actually need to design and build out.

Going forward, we should make an issue for each component to keep track of handoff and progress.

**Comment by alxmrtnz** [comment]
@heyitsolivia I've added all other components to the component sheet 

![component sheet 2-17-16](https://cloud.githubusercontent.com/assets/1167326/13114616/3b5c97b6-d562-11e5-9db0-599c92c21758.jpg)
