### ISSUE TITLE
Component - News Article Cards

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#10]
## Wireframe

![screen shot 2016-02-22 at 3 03 39 pm](https://cloud.githubusercontent.com/assets/1167326/13230939/798c76a2-d975-11e5-9816-e74d08bf8237.png)
## Appears in

About > News
https://invis.io/9X6FZESC4

**Comment by thepaleshadow** [comment]
Single News Article Card: @heyitsolivia @alxmrtnz 
<img width="979" alt="news-article-card" src="https://cloud.githubusercontent.com/assets/14925396/14466155/9fee39f2-00a3-11e6-8784-120c3be8e4ca.png">
