### ISSUE TITLE
Component - Pagination

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#11]
# Wireframe

![screen shot 2016-02-22 at 3 04 11 pm](https://cloud.githubusercontent.com/assets/1167326/13230964/8e64defc-d975-11e5-9116-455d10c89bf4.png)
# Appears in

About > News
https://invis.io/9X6FZESC4

**Comment by thepaleshadow** [comment]
News Pagination: @heyitsolivia @alxmrtnz 
<img width="617" alt="news-pagination" src="https://cloud.githubusercontent.com/assets/14925396/14466177/b9730812-00a3-11e6-86ed-4acd7c7ee515.png">

**Comment by alxmrtnz** [comment]
@thepaleshadow 👍
