### ISSUE TITLE
Component - Single News Article Navigation

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#12]
## Wireframe

![screen shot 2016-02-22 at 3 04 33 pm](https://cloud.githubusercontent.com/assets/1167326/13230980/a4268ace-d975-11e5-8e31-84132890f5db.png)
## Appears in:

About > News > News Article
https://invis.io/VT63IHQ67

**Comment by thepaleshadow** [comment]
Single News Article Pagination as well as Share Links: @heyitsolivia @alxmrtnz 
<img width="764" alt="share-links-article-pagination" src="https://cloud.githubusercontent.com/assets/14925396/14466200/d4774be6-00a3-11e6-99ac-ae8429a739d0.png">

**Comment by alxmrtnz** [comment]
@thepaleshadow 👍
