### ISSUE TITLE
Component - Employees Block

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#13]
## Wireframes

![screen shot 2016-02-22 at 3 05 23 pm](https://cloud.githubusercontent.com/assets/1167326/13230989/b5c044e6-d975-11e5-95d2-8ea43722a22d.png)
### Mobile

![wla-team-small1-4-12-16](https://cloud.githubusercontent.com/assets/1167326/14472642/13da114c-00c2-11e6-9a73-fbf0353e5943.jpg)
### Tablet

![wla-team-medium1-4-12-16](https://cloud.githubusercontent.com/assets/1167326/14472641/0fab6e7c-00c2-11e6-976c-4b31a9f235cc.jpg)
### Desktop

![wla-team-large1-4-12-16](https://cloud.githubusercontent.com/assets/1167326/14470372/1db59552-00b7-11e6-9aea-ef2050722a55.jpg)
## Appears in:

About > Team
https://invis.io/7G62UH3H5

**Comment by alxmrtnz** [comment]
@stacykane I'm starting work on this component and was hoping to get some input from your team.
- About how many Staff members will WLA be starting with?
- About how many Board members will WLA be starting with?
- Will your team be able to provide head shots for each staff/board member? If yes, could you prepare and send a set our way? 
- Do you want only the name and position of each individual or also a small text snippet explaining more about them?
- Do you want the option to display a social media icon/link to each individual's social accounts? (this could be as simple as linking to a LinkedIn profile or could also feature Facebook, Twitter, etc)

I ask these questions because they will influence the design and development decisions of the board/staff page.

Thanks!

**Comment by alxmrtnz** [comment]
@heyitsolivia Just added initial component comps (using real text data, placeholder portraits).

Mobile and tablet are set at the largest width before they'd break to the next level up.

Let me know what you think and we can chat as well

cc: @thepaleshadow

**Comment by stacykane** [comment]
1 - 15 staff to start, adding about 8-10 per year after that until full
capacity in 4 years.
2 - 9 Board Members to start, 15 ever at max capacity but we might not even
get that big.
3 - Head shots yes but might take some time. We will start collecting!!
4 - A small text snippet would also be great!
5 - Yes on social media IF we can also not include it (some of our
staff/members either don't have it or might not want it linked).

Thank you!!

**Comment by heyitsolivia** [comment]
@alxmrtnz @awarehouse  Ready for qa/review!

**Comment by alxmrtnz** [comment]
Just a couple of changes here:

1 - On small, adjust top and bottom margins of team card to the following to decrease the amount of space between each:
<img width="1235" alt="screen shot 2016-04-26 at 4 31 24 pm" src="https://cloud.githubusercontent.com/assets/1167326/14833316/a4e98860-0bcc-11e6-9d09-ae1c4e5a451a.png">

2 - adjust paddings on these blocks to decrease the amount of space between employees and tutors (it looks like we may need to add an additional class to these sections):
<img width="1293" alt="screen shot 2016-04-26 at 4 30 30 pm" src="https://cloud.githubusercontent.com/assets/1167326/14833352/db893398-0bcc-11e6-989f-bb13ec6aefb0.png">
<img width="1293" alt="screen shot 2016-04-26 at 4 30 38 pm" src="https://cloud.githubusercontent.com/assets/1167326/14833353/db8f7456-0bcc-11e6-9453-f977ba998bc4.png">

**Comment by heyitsolivia** [comment]
Padding adjustment is a nice to have.
