### ISSUE TITLE
Component - Summary Block

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#14]
# Wireframe

![screen shot 2016-02-22 at 3 05 50 pm](https://cloud.githubusercontent.com/assets/1167326/13231010/c69a37d6-d975-11e5-927a-1c04797be168.png)
# Visual Design

![wla-component-summary-block-desktop1-3-23-16](https://cloud.githubusercontent.com/assets/1167326/14000819/569da592-f119-11e5-9f92-1cfc6ac4b9df.jpg)
# Notes
## Character Count

![character count wla-component-summary-block-desktop1-3-23-16](https://cloud.githubusercontent.com/assets/1167326/14118953/e7a21dee-f5b9-11e5-916f-5fb9c595856a.jpg)

**Comment by heyitsolivia** [comment]
@awarehouse @alxmrtnz This is ready for QA and Content

**Comment by awarehouse** [comment]
@heyitsolivia The summary block needs padding. https://www.dropbox.com/s/a8gg84qe6xemew5/Screenshot%202016-04-22%2015.43.22.png?dl=0

**Comment by heyitsolivia** [comment]
Fixed in #57

**Comment by alxmrtnz** [comment]
@heyitsolivia this looks good upon review :+1:
