### ISSUE TITLE
Component - Media Highlights

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#15]
# Wireframe

![screen shot 2016-02-22 at 3 07 00 pm](https://cloud.githubusercontent.com/assets/1167326/13231059/f98f536a-d975-11e5-9613-c16b001ffa44.png)
# Visual Design
## Desktop (3-21-16)

![wla-component-media-highlights-desktop1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938410/ffe05c0c-efa3-11e5-89a5-92c5ff8079e2.jpg)
## Tablet (3-21-16)

![wla-component-media-highlights-tablet1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938524/0529b3ca-efa4-11e5-9b5b-0b0bf0ccc3c2.jpg)
## Mobile (3-16-21)

![wla-component-media-highlights-mobile1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938670/099b4dce-efa4-11e5-8612-c530646d996a.jpg)
# Notes
## Character Count

![character count wla-component-media-highlights-desktop1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/14118978/032e08e8-f5ba-11e5-9344-9f464ead9c99.jpg)

**Comment by alxmrtnz** [comment]
@heyitsolivia 

First draft of mobile and tablet for this component:

![wla-component-media-highlights-tablet1-3-2-16](https://cloud.githubusercontent.com/assets/1167326/13465625/8cc47dc8-e064-11e5-85a5-77ad1ae29870.jpg)

![wla-component-media-highlights-mobile1-3-2-16](https://cloud.githubusercontent.com/assets/1167326/13465631/91edc336-e064-11e5-95af-6a3f4ca83b57.jpg)

**Comment by heyitsolivia** [comment]
@stacykane I have a question

**Comment by stacykane** [comment]
@heyitsolivia I have an answer!

**Comment by alxmrtnz** [comment]
@heyitsolivia ,

I've updated this issue with updated comps. The main difference being an update to the serif typeface (we're now using Domine instead of Sentinel)

**Comment by heyitsolivia** [comment]
@awarehouse @alxmrtnz This media block is ready for QA and content too

**Comment by awarehouse** [comment]
@heyitsolivia Question about the middle "Call Out" Section. Does the call out text only appear if you have a link? In the Homepages' case we have a quote there. Does that mean the author's name wouldn't be visible?

**Comment by heyitsolivia** [comment]
@awarehouse 

**Callout text** should always be displayed.
**Callout link text** is only displayed if you have also added a **callout link url**.

Not sure about the author bit— I don't have a field for you to enter an "author name", I don't think using the Callout section as a quote area was a use case for that component. If you're putting in an author name in the Callout Link Text, then it wouldn't be displayed without a link.

Is that a case I should handle or can you just use the quote block for this purpose?

**Comment by awarehouse** [comment]
@heyitsolivia Their preference is to have the middle call out treated like a quote block. Is this possible?

**Comment by alxmrtnz** [comment]
@heyitsolivia @awarehouse I designed the block to serve as an announcement block that the user could enter sentence long announcements with or without a link. That could mean that a quote could also go there, but as we designed it, there was no intention for a quote attribution. If they'd like that, I think we could add it.

**Comment by awarehouse** [comment]
@alxmrtnz Is it weird to use a quote and not include the quote credit? cc @heyitsolivia

**Comment by alxmrtnz** [comment]
@heyitsolivia something that I'm noticing just now is that on both this component and the employee page (#13) is that the triangle caret is not perfectly centered (it's slightly off to the right)

![screen shot 2016-04-26 at 2 32 50 pm](https://cloud.githubusercontent.com/assets/1167326/14829901/dfe29d28-0bbb-11e6-8bbf-1205d4877b32.png)

**Comment by alxmrtnz** [comment]
@heyitsolivia only other thing I'd change would be to decrease the margin-bottom of .mediablock .summary__header from 4rem to 3rem

**Comment by alxmrtnz** [comment]
@heyitsolivia  Just found a couple of issues with widths of text in this component on IE 10 (it looks fine in IE 11)

<img width="1157" alt="screen shot 2016-04-26 at 4 00 11 pm" src="https://cloud.githubusercontent.com/assets/1167326/14832623/238e8ed0-0bc9-11e6-83a8-04af7e365aa2.png">
<img width="1157" alt="screen shot 2016-04-26 at 4 00 22 pm" src="https://cloud.githubusercontent.com/assets/1167326/14832622/238a4b72-0bc9-11e6-978e-6c4c1dd16079.png">
<img width="397" alt="screen shot 2016-04-26 at 4 00 52 pm" src="https://cloud.githubusercontent.com/assets/1167326/14832624/2391cbc2-0bc9-11e6-8efa-cc04f00e8d59.png">

This text width may be causing problems in these other two components:

<img width="399" alt="screen shot 2016-04-26 at 4 01 20 pm" src="https://cloud.githubusercontent.com/assets/1167326/14832639/2fe94a4e-0bc9-11e6-8584-0ec94e489d89.png">
<img width="399" alt="screen shot 2016-04-26 at 4 01 44 pm" src="https://cloud.githubusercontent.com/assets/1167326/14832646/352ade1e-0bc9-11e6-8292-16628c15e4d6.png">
