### ISSUE TITLE
Component: Callout - Image Highlights

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#16]
# Wireframe

![screen shot 2016-02-22 at 3 07 41 pm](https://cloud.githubusercontent.com/assets/1167326/13231072/0888c464-d976-11e5-8966-65384d7e3866.png)
# Visual Design
## Desktop

![wla-component-callout-three-column-desktop1-3-29-16](https://cloud.githubusercontent.com/assets/1167326/14219421/37649990-f828-11e5-8bd2-62abf9c42508.jpg)
## Tablet

![wla-component-callout-three-column-tablet-3-29-16](https://cloud.githubusercontent.com/assets/1167326/14219424/3b3d6e98-f828-11e5-9c49-10abd3ede149.jpg)
## Mobile

![wla-component-callout-three-column-mobile1-3-29-16](https://cloud.githubusercontent.com/assets/1167326/14219426/3fd6f6fe-f828-11e5-91fe-54ced6f647b8.jpg)
# Notes
- "In the Future": Heading Medium
- Each heading for the callout should Heading Small
- Paragraphs: Paragraph Small
## Character Count

![character count wla-component-callout-three-column-desktop1-3-29-16](https://cloud.githubusercontent.com/assets/1167326/14219434/466a76ee-f828-11e5-8c70-33a10d2d194b.jpg)

**Comment by heyitsolivia** [comment]
@alxmrtnz Update comp for review purposes

**Comment by alxmrtnz** [comment]
@heyitsolivia updated!

**Comment by alxmrtnz** [comment]
@heyitsolivia @thepaleshadow any thoughts on this? If it's fine with both of you, we can move it to Ready for Dev

**Comment by heyitsolivia** [comment]
@awarehouse @alxmrtnz Ready for qa/review!

**Comment by alxmrtnz** [comment]
1. on mobile, decrease margin-bottom of `.highlight__title` to .25rem (this also applies to #17 )
2. on mobile and tablet, set highlight `margin: .5rem 2rem`
3. on mobile and tablet, decrease highlight__image's margin bottom from 2rem to 1rem

All of these things should help tighten up each highlights in this component and the text highlights compoentn (#17) on tablet and mobile.
