### ISSUE TITLE
Component: Callout - Text Highlights

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#17]
# Wireframes

![screen shot 2016-02-22 at 3 08 11 pm](https://cloud.githubusercontent.com/assets/1167326/13231086/1ff25e8a-d976-11e5-8ee5-a48ccb0144ce.png)
# Visual Design
## Desktop

![wla-component-callout-text-highlights-desktop1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14219293/8a2f6aca-f827-11e5-9a2d-3a180c0acf44.jpg)
## Tablet

![wla-component-callout-text-highlights-tablet1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14219298/8f0898aa-f827-11e5-8a9a-5ee0ad1378c7.jpg)
## Mobile

![wla-component-callout-text-highlights-mobile1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14219301/929310cc-f827-11e5-84a4-f78a5919e4a3.jpg)
# Notes
- Main heading: Heading Medium
- Main Paragraph: Paragraph Medium
- Text highlights: Paragraph small
## Character Count

![character count wla-component-callout-text-highlights-desktop1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14219307/96b96c82-f827-11e5-8217-214ba7bdd2fb.jpg)

**Comment by awarehouse** [comment]
@alxmrtnz I still need the character count for this section.

**Comment by alxmrtnz** [comment]
@awarehouse just added visual design and character counts for this component

**Comment by heyitsolivia** [comment]
@alxmrtnz Have you tried a dark text color for this component? We'll run into accessibility issues with that white text on the gold background. It's currently failing content accessibility guidelines, see a test here: http://jxnblk.com/colorable/demos/text/?background=%23ffb42d&foreground=%23FFF

**Comment by alxmrtnz** [comment]
@heyitsolivia it looks like using our black for the text color passes the test.

A change like that will affect this testimonial component and also the 3 column callout.

@thepaleshadow what do you think on how these look? When you have a chance could you swing by my desk?

<img width="1552" alt="screen shot 2016-03-29 at 4 41 50 pm" src="https://cloud.githubusercontent.com/assets/1167326/14123281/cb7cb142-f5cd-11e5-951e-2a4b36dfe314.png">
<img width="1552" alt="screen shot 2016-03-29 at 4 41 58 pm" src="https://cloud.githubusercontent.com/assets/1167326/14123286/cf9b9dec-f5cd-11e5-8816-3c2e7cbafb14.png">
<img width="1552" alt="screen shot 2016-03-29 at 4 42 56 pm" src="https://cloud.githubusercontent.com/assets/1167326/14123293/d1eec40c-f5cd-11e5-9af8-e1625da2739e.png">

**Comment by alxmrtnz** [comment]
@heyitsolivia after checking with @thepaleshadow, in order to make the text/background color accessible:

Let's move forward with using our Indigo color for any text on a teal or gold background (this will include the mobile navigation drawer).

**Comment by heyitsolivia** [comment]
@alxmrtnz So you want text color change to carry into the nav like so?
<img width="403" alt="screen shot 2016-03-29 at 4 58 58 pm" src="https://cloud.githubusercontent.com/assets/1198350/14123685/c4cbf838-f5cf-11e5-979f-dc1f1e7ab819.png">

**Comment by thepaleshadow** [comment]
That looks dope ^. So much more legible. @alxmrtnz @heyitsolivia

**Comment by alxmrtnz** [comment]
@heyitsolivia yep! I'd make the shield, the "x" and the text in that subscribe to newsletter button all navy as well

**Comment by heyitsolivia** [comment]
Notes from discussion: Leave logo and menu icon as is, update nav text, button, and underline to indigo.

**Comment by heyitsolivia** [comment]
@alxmrtnz Update comp for review purposes

**Comment by alxmrtnz** [comment]
@heyitsolivia updated comps for this component!

**Comment by heyitsolivia** [comment]
@awarehouse @alxmrtnz Ready for qa/review!

**Comment by alxmrtnz** [comment]
looks good to me! 👍

**Comment by alxmrtnz** [comment]
Actually, the only thing I'd change is to remove the feint white line under the intro paragraph. I'm not sure if you intentionally added it to create separation? If you think it's better with the line, feel free to keep :)

![screen shot 2016-04-25 at 1 42 06 pm](https://cloud.githubusercontent.com/assets/1167326/14793128/974aabb2-0aeb-11e6-9f90-bb613c7d787d.png)

**Comment by heyitsolivia** [comment]
@alxmrtnz Ah yeah, I added the line to create some distinction between the summary and sections, since it was starting to  feel like a wall of text to me. Thoughts? We can try some other treatment or remove it entirely if you think it's not working.

**Comment by alxmrtnz** [comment]
@heyitsolivia If we keep the seperator, let's go with a darker version. (either just darken what we have to something like rgba(0,0,0,.1) or use an after element to create a smaller width version of it

option 1
![screen shot 2016-04-25 at 2 00 06 pm](https://cloud.githubusercontent.com/assets/1167326/14793602/0fd35636-0aee-11e6-9739-13f0e1d11324.png)

option2
<img width="1231" alt="screen shot 2016-04-25 at 1 55 03 pm" src="https://cloud.githubusercontent.com/assets/1167326/14793603/0fd5c0a6-0aee-11e6-9c50-6643b47a722d.png">

**Comment by alxmrtnz** [comment]
@heyitsolivia moving this to QA fix for now

**Comment by heyitsolivia** [comment]
Let's go with option A
