### ISSUE TITLE
Component - Image Gallery

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#18]
Wireframes

![screen shot 2016-02-22 at 3 09 27 pm](https://cloud.githubusercontent.com/assets/1167326/13231124/47b715f0-d976-11e5-9d5a-f30ff01885e6.png)

**Comment by heyitsolivia** [comment]
Note: Explore using the built in Squarespace gallery block

**Comment by heyitsolivia** [comment]
@alxmrtnz Was there a comp for this?

**Comment by alxmrtnz** [comment]
@heyitsolivia There is not currently a comp. We had discussed possibly using Squarespace's build in gallery component. Could you look into what's available and then we can sync early this next week?

**Comment by heyitsolivia** [comment]
@awarehouse @alxmrtnz Ready for qa/review!

**Comment by alxmrtnz** [comment]
Looks good! 

One thing is that I think the images should be bigger on mobile

something like this:
<img width="398" alt="screen shot 2016-04-25 at 2 03 07 pm" src="https://cloud.githubusercontent.com/assets/1167326/14793694/81f1809e-0aee-11e6-96b2-10db9196bff1.png">
