### ISSUE TITLE
Duplicate Issue - Deleted CTA Block

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#19]
## Wireframes

![image](https://cloud.githubusercontent.com/assets/16227787/13848136/df59b51c-ec26-11e5-9091-cd0cce0f799c.png)
### Desktop

![wla-component-cta-desktop1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938837/e4dae57e-efa5-11e5-8dfa-b5e338773afb.jpg)
## Tablet

![wla-component-cta-tablet1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938846/efa094ae-efa5-11e5-8799-12e6be4f2de7.jpg)
## Mobile

![wla-component-cta-mobile1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938852/f4aae508-efa5-11e5-858f-4fe11d9037ab.jpg)
## Notes
- WLA should have the ability to swap out the image in this component. I'd recommend having the image cover the background and placing a navy gradient between it and the text.

**Comment by awarehouse** [comment]
@alxmrtnz Are we going to treat the CTA Testimonial and the regular Quote Block as separate components?  cc @heyitsolivia

**Comment by heyitsolivia** [comment]
@awarehouse I think that is what we last decided, yes

**Comment by alxmrtnz** [comment]
@awarehouse @heyitolivia, yep! Separate indeed

**Comment by awarehouse** [comment]
@heyitsolivia @alxmrtnz Hey guys both tickets have been updated.

**Comment by alxmrtnz** [comment]
@heyitsolivia @awarehouse updated visual design for this component has been added

**Comment by awarehouse** [comment]
@alxmrtnz Is this the ticket that you deleted? If not, should this ticket really be assigned to @heyitsolivia to dev?

**Comment by alxmrtnz** [comment]
@awarehouse this is the ticket I closed. You can see that it's been marked as closed at the top of this page :)
