### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#2]
Feb 9, 2016
Documenting a bit of our wireframing process: The internal team cut apart our first round of wireframes to determine which components to keep, cut, and reuse across the sites' various pages.

![screen shot 2016-02-10 at 2 53 27 pm](https://cloud.githubusercontent.com/assets/1167326/12959779/0d935934-d006-11e5-8d68-56e887937e95.png)

![image](https://cloud.githubusercontent.com/assets/1167326/12959729/be02280a-d005-11e5-9780-8498e0eceed8.png)

**Comment by alxmrtnz** [comment]
Round 1 Wireframes presented by ISL to WLA on Feb. 10, 2016

Invision project link for the wireframes: 
https://invis.io/495Z2EAEC

# **Homepage**

![1 wla-homepage](https://cloud.githubusercontent.com/assets/1167326/12958964/44dc5d7c-d002-11e5-9fac-f48ae948b41c.jpg)

# **About Overview**

![2 wla-about](https://cloud.githubusercontent.com/assets/1167326/12958981/5ac00a76-d002-11e5-9e73-d84ecc42cac7.jpg)

# **About - Founding Story**

![3 wla-about-foundingstory](https://cloud.githubusercontent.com/assets/1167326/12958998/6bb27f08-d002-11e5-9c4a-b2b9226678c8.jpg)

# **About - Our Approach**

![4 wla-about-our approach](https://cloud.githubusercontent.com/assets/1167326/12959005/7a22900a-d002-11e5-8362-4af44b0dc222.jpg)

# **About - Team**

![5 wla-about-team](https://cloud.githubusercontent.com/assets/1167326/12959015/8799979c-d002-11e5-8524-254b71dd128e.jpg)

# **About - News**

![6 wla-about-news](https://cloud.githubusercontent.com/assets/1167326/12959020/8e409d52-d002-11e5-93f4-143ede990875.jpg)

# **About - Single News Article**

![7 wla-about-news - single article](https://cloud.githubusercontent.com/assets/1167326/12959027/93cabece-d002-11e5-8afb-1940993ce378.jpg)

# **Academics**

![8 wla-academics](https://cloud.githubusercontent.com/assets/1167326/12959035/a1cdf180-d002-11e5-9e4e-4db46efb0279.jpg)

# **Student Life**

![9 wla-student-life](https://cloud.githubusercontent.com/assets/1167326/12959047/ae8bb7ae-d002-11e5-87a6-60eecde69c82.jpg)

# **Events**

![10 wla-events](https://cloud.githubusercontent.com/assets/1167326/12959055/b6e696c6-d002-11e5-83cd-e354c8b9d086.jpg)

# **Donate**

![11 wla-donate](https://cloud.githubusercontent.com/assets/1167326/12959061/bc9e5dc4-d002-11e5-8ee2-c2cf5b6bac2a.jpg)

# **Contact**

![12 wla-contact](https://cloud.githubusercontent.com/assets/1167326/12959069/c1e512dc-d002-11e5-8114-f881bb383996.jpg)

# **How to Enroll**

![13 wla-howtoenroll](https://cloud.githubusercontent.com/assets/1167326/12959075/c720db28-d002-11e5-828a-86b2ef8d2db2.jpg)

**Comment by alxmrtnz** [comment]
@heyitsolivia 

I've put together updated wireframes and templates in this Dropbox folder:
https://www.dropbox.com/sh/yflrx5fk0iu0m1c/AADVpXz00CRcFlfM_mHK_ppya?dl=0

3 folders in there:
1) Component Sheet

2) Templates
 I put together 5 templates that can be used for the various inner content pages. 

3) Wireframed Pages
What I did here was 2 things. First, I include any unique pages that don't fall into one of the five inner page templates (pages like the homepage or news). Second, I used the 5 templates to wireframe the various inner pages. I've titled each page's wireframe with the template number the page is using so that we can see how they line up with the proposed templates.

If you could take a look today and get me feedback by EOD, that would be awesome!

Thanks :)

cc: @awarehouse

**Comment by heyitsolivia** [comment]
@alxmrtnz I think overall these are looking good, and the templates make sense to me :+1: 
For the component sheet, see my comment in #1

**Comment by alxmrtnz** [comment]
@heyitsolivia @awarehouse 

I've put the updated wireframes into Invision if you would like to check them out there as well:
https://invis.io/3Y62LVW2U

**Comment by awarehouse** [comment]
@alxmrtnz I just looked through the invision link and I saw the changes that you made. I think these templates make a lot of sense, but I had 2 edits / questions. Let me know if you run into any questions.

**Comment by alxmrtnz** [comment]
@heyitsolivia I updated the homepage wireframe in the Invision prototype and is available fully completed here:

https://invis.io/495Z2EAEC
