### ISSUE TITLE
Component - Call to Action (CTA)

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#24]
## Wireframes

![image](https://cloud.githubusercontent.com/assets/16227787/13848136/df59b51c-ec26-11e5-9091-cd0cce0f799c.png)
### Desktop

![wla-component-cta-desktop1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938837/e4dae57e-efa5-11e5-8dfa-b5e338773afb.jpg)
## Tablet

![wla-component-cta-tablet1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938846/efa094ae-efa5-11e5-8799-12e6be4f2de7.jpg)
## Mobile

![wla-component-cta-mobile1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938852/f4aae508-efa5-11e5-858f-4fe11d9037ab.jpg)
## Notes
- WLA should have the ability to swap out the image in this component. Recommendation: have the image cover the background and placing a navy gradient between it and the text.
## Character Count

![wla-component-cta-desktop1-3-21-16](https://cloud.githubusercontent.com/assets/1167326/14119085/820eb9f0-f5ba-11e5-9fad-f42a9e44b4dc.jpg)

**Comment by alxmrtnz** [comment]
@heyitsolivia @awarehouse I closed the duplicate issue and moved everything to this issue

**Comment by alxmrtnz** [comment]
@heyitsolivia looks good upon cross-browser inspection :+1:
