### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#25]
## Wireframes

![1 wla-homepage - unique](https://cloud.githubusercontent.com/assets/1167326/13882747/30043376-ecfd-11e5-9cc8-a90f86311962.jpg)
#### 3-23-16

![assembled-homepage-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14219846/94fc6efa-f82a-11e5-943b-fb224f68323f.png)
# Component List
- Homepage Hero
- Summary block
- Callout - Icons
- Media Highlights
- Testimonial
- CTA Block
- Footer

Design
- [x] Wireframes
- [x] Full page comp
- [x] List of Components

**Comment by awarehouse** [comment]
@alxmrtnz Please design icons for the "What we offer?" section: 
- Computer science and coding
- Real world internships
- The Country's best teachers

**Comment by alxmrtnz** [comment]
@awarehouse @heyitsolivia updated!
