### ISSUE TITLE
[Asset] Production-ready WLA logo

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#29]
As a developer I want to use an SVG logo so the logo looks and feels crispy.

**Versions needed:**
- [x] White knocked out version
- [x] Color version

**Dev Task**
- [x] Add logo assets

**Comment by heyitsolivia** [comment]
Not sure if we will actually need a color version, since I haven't seen one used in the comps, @alxmrtnz can you confirm?

**Comment by alxmrtnz** [comment]
@heyitsolivia , Confirmed. We only need a white version for now.

**Comment by thepaleshadow** [comment]
Final SVG files here, in full signature, wordmark, and logomark isolations:
https://www.dropbox.com/sh/iy9e3an96b2b2dk/AAAvxmThCVdUW7nSZaPOMgtma?dl=0

**Comment by heyitsolivia** [comment]
@thepaleshadow Thanks! I'll put this in ready for dev.

**Comment by heyitsolivia** [comment]
@thepaleshadow Per branding/identity guidelines, the WLA mark can be used on its own without the accompanying wordmark, correct? Just wanted to double check since I want to make this responsive — where on very small screens, you'll only see the logomark instead of the full lockup.

**Comment by thepaleshadow** [comment]
Yep, that’s correct. Use the logomark if the full signature would be rendered illegible, as the guidelines indicate
