### ISSUE TITLE
Component - Alert Bar

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#3]
## Wireframe

![screen shot 2016-02-22 at 2 55 24 pm](https://cloud.githubusercontent.com/assets/1167326/13230684/5878af7c-d974-11e5-9d2b-10a79980c9e1.png)
## Appears in

Home
https://invis.io/495Z2EAEC

**Comment by heyitsolivia** [comment]
Something to keep in mind when you're designing this, the Squarespace CMS likely won't allow us to do that floating link on the right.

It takes a single line of text that can be bolded, italicized, and/or linked.

**Comment by heyitsolivia** [comment]
@alxmrtnz  Looks like this (Squarespace defaults: close icon, text and/or link), the "alert" text is content in a pseudo element I added, but we can change/remove this.)

<img width="828" alt="screen shot 2016-04-01 at 11 08 32 am" src="https://cloud.githubusercontent.com/assets/1198350/14211082/2e27d3fc-f7fa-11e5-9ccb-f2d97400d4dc.png">

**Comment by thepaleshadow** [comment]
Alert Bar: @alxmrtnz @heyitsolivia 
<img width="1440" alt="alert-bar" src="https://cloud.githubusercontent.com/assets/14925396/14466250/f90b2d74-00a3-11e6-98fa-10698edc9ff8.png">

**Comment by alxmrtnz** [comment]
@thepaleshadow the only other change I'd say is to add an underline to "Read More". I know we don't do so with other links, but because it's the same color and weight as the word "Alert", it may be good to distinguish it.

Other option would be to add an arrow-right like we do with other links, but I'm not sure that's possible with the html structure of what Squarespace provides. @heyitsolivia , could you consult here? If we can't add an arrow, I'd say we just use the underline.

**Comment by heyitsolivia** [comment]
@alxmrtnz @thepaleshadow Since this markup is being injected by Squarespace and the content by the user, we don't have much control over what shows up here. The user could create link(s) anywhere in that line of text. As such, we also can't/shouldn't control the spacing around that link.

We can add that **ALERT** as a pseudo element, but the user can't modify that. It would always show up, not sure if that's really a good idea. @awarehouse Can you weigh in here?

**Comment by awarehouse** [comment]
@alxmrtnz @thepaleshadow @heyitsolivia Let's hard code "ALERT" into the alert bar. The purpose of this bar is to alert users of emergencies. We don't want this bar used as a random CTA bar.

**Comment by heyitsolivia** [comment]
sounds good, I'll move this into Ready for Dev

**Comment by alxmrtnz** [comment]
@heyitsolivia this one looks good to go :+1:
