### ISSUE TITLE
Design for a 404 page

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#30]
As a user, I want to see a decent looking 404 error page if I happen upon a page that doesn't exist.

(Note: This doesn't explicitly need to say "404")

**Comment by heyitsolivia** [comment]
@alxmrtnz Can you add your comp to this ticket please?

**Comment by alxmrtnz** [comment]
@heyitsolivia sure thing!

![wla-404](https://cloud.githubusercontent.com/assets/1167326/14469330/23f45836-00b2-11e6-840d-6aef6e7de557.png)

cc:  Olivia and @thepaleshadow: ready for design review

**Comment by heyitsolivia** [comment]
@alxmrtnz Looks good to me. Wonder if the tiled pattern @thepaleshadow is working on could look good on the background of this page?

**Comment by heyitsolivia** [comment]
@alxmrtnz I think this still needs QA, you can access this page by going to `/404`

**Comment by alxmrtnz** [comment]
@heyitsolivia just decrease the .errorblock svg `margin-bottom` to `3rem` instead of `4rem` and I think it's good to go
