### ISSUE TITLE
Component - Testimonial

### ISSUE THREAD

**Issue by awarehouse** [washington-leadership-academy/wla#31]
## Wireframes

![screen shot 2016-02-22 at 3 09 44 pm](https://cloud.githubusercontent.com/assets/1167326/13231138/5a57ae5e-d976-11e5-8925-b6768f28fb56.png)
### Desktop

![wla-component-testimonial-desktop1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14218894/11e17704-f825-11e5-8ce1-cb00a62d71d9.jpg)
### Tablet

![wla-component-testimonial-tablet1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14218896/12a5cd84-f825-11e5-8ef0-edae7706546c.jpg)
### Mobile

![wla-component-testimonial-mobile1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14218899/16b6566e-f825-11e5-9af1-bfb9e4eb745e.jpg)
# Notes
## Character Count

![character count wla-component-testimonial-desktop1-4-1-16](https://cloud.githubusercontent.com/assets/1167326/14218903/1b432018-f825-11e5-90bf-51762a2ff84f.jpg)

**Comment by alxmrtnz** [comment]
@heyitsolivia @awarehouse visual design for this component has been added

**Comment by alxmrtnz** [comment]
@heyitsolivia @awarehouse updated visual design and character counts have been added above

**Comment by heyitsolivia** [comment]
@alxmrtnz update text color

**Comment by alxmrtnz** [comment]
@heyitsolivia updated!

**Comment by heyitsolivia** [comment]
Two things:
- I set up author and author position on the same line as I'm not sure we will need 2 lines. But if the content works better with two lines, I can make that change.
- I included curly quotes on all quote text as part of the template, thought that would be easiest.

**Comment by alxmrtnz** [comment]
@heyitsolivia only two things I can find to modify before this is good to go:

1 - on mobile, let's decrease the margin-bottom on .quoteblock__image from 2rem to 1.5rem
2 - at all screensizes, make the padding-top 1rem less than the padding-bottom. Visually, this will help the content look more centered vertically (even though it's really not)
- Mobile: top: 6rem, bottom: 7rem
- Tablet: top: 7rem, bottom: 8rem
- Desktop: top: 11rem, bottom 12rem

It's kind of like in framing artwork, you cut the matte frame to be shorter at the top, larger at the bottom to accommodate for how people's eyes will be viewing at an angle.

![image](https://cloud.githubusercontent.com/assets/1167326/14830521/16e5d12a-0bbf-11e6-8fe7-272950b7c471.png)
