### ISSUE TITLE
Web typography

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#32]
Determine final typography for the site.
- [x] List of final typefaces and weights/styles
- [x] Determine web solution (Preferably Google Fonts or Typekit)

**Comment by thepaleshadow** [comment]
![wla-brand-typefaces](https://cloud.githubusercontent.com/assets/14925396/13958394/4cac2d4a-f026-11e5-8258-081dad007974.jpg)

All brand typefaces are from Google Fonts. Desktop files can be found here: https://www.dropbox.com/sh/979t0igw1ekrewe/AAAUIGGT6WQRXdvlADZTeozga?dl=0

**Comment by heyitsolivia** [comment]
Added the following webfonts to the project:
- Domine: 400
- Montserrat: 700
- Source Sans Pro: 400, 400italics, 700, 700italics
