### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#33]
**Final color palette**

<img width="1178" alt="screen shot 2016-03-17 at 6 39 19 pm" src="https://cloud.githubusercontent.com/assets/1198350/13863358/a2180e1c-ec6f-11e5-8550-61b099175a19.png">

| Color | Hex Value |
| --- | --- |
| Deep Indigo | #161E3A |
| Gold | #FFB42D |
| Jersey White | #F2F7F9 |
| Sea Mint | #6BD8D3 |

**Dev Tasks**
- [ ] Set colors up as sass variables

**Comment by thepaleshadow** [comment]
Final color palette w/ hex & rgb values can be found here:
https://www.dropbox.com/s/cv8z2851sz027ci/WLA-Color-Renderings-Final.pdf?dl=0

**Comment by heyitsolivia** [comment]
<img width="1178" alt="screen shot 2016-03-17 at 6 39 19 pm" src="https://cloud.githubusercontent.com/assets/1198350/13863358/a2180e1c-ec6f-11e5-8550-61b099175a19.png">

| Color               | Hex Value  |
| ------------------- | --------------- |
| Deep Indigo | #161E3A |
| Gold | #FFB42D |
| Jersey White | #F2F7F9
| Sea Mint | #6BD8D3

**Comment by heyitsolivia** [comment]
@alxmrtnz Can you check to see if there are any additional colors from your comps that should be added to the list above? I thought I saw an orange somewhere.

**Comment by alxmrtnz** [comment]
@heyitsolivia @thepaleshadow 

In my comps, I've used a slightly different "jersey white" for section backgrounds.

#F2F4F9 instead of #F2F7F9. I wouldn't bring it up (since they're so close) except for that I think the option I have has a bit more blue and looks better on the site.

Also, **Olivia**, we've switched from orange to gold. The components/comps I post shortly will have that updated color.

**Comment by heyitsolivia** [comment]
@thepaleshadow If we're using `#F2F4F9` in the comps and site, then should we update the brand/color guidelines to reflect that?

**Comment by thepaleshadow** [comment]
@heyitsolivia: We’re no longer using that hex code—sticking to #F2F7F9

**Comment by heyitsolivia** [comment]
Thanks! Moving this to dev now.
