### ISSUE TITLE
Web Typography guidelines

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#34]
Define typography to be used across the site, including headings, subheadings, body text, labels, callouts, etc.

**Comment by alxmrtnz** [comment]
@thepaleshadow @heyitsolivia 

I've put together a doc of web type::

![type styles 4-1-16](https://cloud.githubusercontent.com/assets/1167326/14219123/7b1353c2-f826-11e5-917a-775afce7dfe4.jpg)

I'm out Thursday and Friday, but if either of you want to check out the source, it's in the "WLA Components" sketch file located here on dropbox:
https://www.dropbox.com/sh/ogb59kqe99cii0m/AABJ5Q_McElImdZ7oDh2guCWa?dl=0

The type styles are in the page "Type Styles" within that component document:
<img width="1552" alt="screen shot 2016-03-23 at 9 28 37 pm" src="https://cloud.githubusercontent.com/assets/1167326/14005943/98183792-f13e-11e5-8d20-8a2f3d8316f2.png">

**Comment by thepaleshadow** [comment]
Awesome, @alxmrtnz! These look great so far.

**Comment by heyitsolivia** [comment]
@alxmrtnz Add heading small guidelines

**Comment by alxmrtnz** [comment]
@heyitsolivia updated!

**Comment by heyitsolivia** [comment]
These can be reviewed on this temporary styleguide page: https://washingtonleadershipacademy.squarespace.com/styleguide

**Comment by alxmrtnz** [comment]
@heyitsolivia marking this as done
