### ISSUE TITLE
Email Newsletter Link

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#35]
We need a link to WLA's current email newsletter sign up.

**Comment by awarehouse** [comment]
@stacykane @nataliegould Can you please send us the link to your current email newsletter sign up?

**Comment by stacykane** [comment]
Hi Arista! We haven't set it up yet. I think we are going to use Mail Chimp
but we haven't set it up. Right now we use google groups which I don't
think we want to stay with.

**Comment by awarehouse** [comment]
@stacykane @nataliegould  Can you please try to have the Mail Chimp set up by April 8th?

**Comment by nataliegould** [comment]
Hey - we set up a free account. Do you need login credentials?

NG

On Fri, Apr 1, 2016 at 11:07 AM, Arista notifications@github.com wrote:

> @stacykane https://github.com/stacykane @nataliegould
> https://github.com/nataliegould Can you please try to have the Mail
> Chimp set up by April 8th?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/washington-leadership-academy/wla/issues/35#issuecomment-204432339

## 

_Natalie Gould_
Director of Operations
Washington Leadership Academy
612-867-3829
www.linkedin.com/in/natalieagould
http://washingtonleadershipacademy.org/
http://washingtonleadershipacademy.org/

**Comment by awarehouse** [comment]
Yes. That would be great. Thank you!
