### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by awarehouse** [washington-leadership-academy/wla#36]

**Comment by alxmrtnz** [comment]
@thepaleshadow I'm assigning this to you as master of the WLA crest. If you could put together a 260px by 260px comp for a favicon, I can help reformat it to the size we need. 

It can either have a color or transparent background.

**Comment by thepaleshadow** [comment]
@alxmrtnz Link to the favicon can be found [here.](https://www.dropbox.com/s/jlw8oxebr1q6u1i/wla-favicon.png?dl=0)

**Comment by heyitsolivia** [comment]
@thepaleshadow We may want a transparent background for the browser favicon.

For touch icons (the icon that shows up when you bookmark a page to your phone's homescreen) this would work fine.
