### ISSUE TITLE
Component - Navigation

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#4]
### Wireframe

![screen shot 2016-02-22 at 2 56 33 pm](https://cloud.githubusercontent.com/assets/1167326/13230722/79725dae-d974-11e5-8a2b-38c9dcd43034.png)
#### Desktop

![wla-component-navigation-desktop1-3-2-16](https://cloud.githubusercontent.com/assets/1167326/13861067/ba6b3880-ec61-11e5-975f-b77c2145f445.jpg)

Hover States
Example hover style [here](http://tympanus.net/Development/CreativeLinkEffects/)
![wla-component-navigation-desktop2-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13881615/f47cf1c6-ecf7-11e5-830a-1b798321dea7.jpg)

![wla-component-navigation-desktop3-3-17-16](https://cloud.githubusercontent.com/assets/1167326/13881621/f8cde2f8-ecf7-11e5-9690-10a1fc0be0ac.jpg)
#### Tablet

![wla-component-navigation-tablet1-3-17-16](https://cloud.githubusercontent.com/assets/1167326/13861063/b6cc31f2-ec61-11e5-900f-45d8a6470153.jpg)

![wla-component-navigation-tablet2-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13881658/1b8a98cc-ecf8-11e5-878b-02e55b242aad.jpg)

Hover State - Subscribe
![wla-component-navigation-tablet3-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13881663/1ea95ce6-ecf8-11e5-8a4f-0d9e0ce132bc.jpg)
#### Mobile

![wla-component-navigation-mobile1-3-17-16](https://cloud.githubusercontent.com/assets/1167326/13861071/c353b4e0-ec61-11e5-8127-cd2785d9a054.jpg)

![wla-component-navigation-mobile2-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13881672/28e14fc0-ecf8-11e5-9f04-f9fa02583420.jpg)
### Design Tasks
- [x] Nav component for small screens
- [x]  Nav component for large screens
- [x]  Navigation links — hover/active/focus states
### Dev Tasks
- [ ]
### Acceptance
- [ ] Navigation items are accurate per comp
- [ ] Navigation is responsive
- [ ] Hover states are present
- [ ] Active states are present

**Comment by heyitsolivia** [comment]
**Visual design needed for the following states**
- [x] Nav component for small screens
- [x] Nav component for large screens
- [x] Navigation links — hover/active/focus states

**Comment by alxmrtnz** [comment]
@heyitsolivia @thepaleshadow visual design for navigation added for review.

**Comment by heyitsolivia** [comment]
@alxmrtnz Looking good. Some questions:
- Will the navigation always be displayed on a dark background (solid/photo)?
- Are there current/hover states for menu items on smaller screens? So the user can see the current page they are on highlighted in some way.
- Are there hover/active states for the subscribe/newsletter link? Maybe the background of the button/tab  darkens?
- If the user is on a subpage (for example, `/about/our-story`), will the parent group (`about`) be highlighted? For context, right now clicking on `/about` will take you to the first subpage created underneath it—per wireframes, this would be `about/overview`. `/about` wouldn't exist as a standalone page.

**Comment by alxmrtnz** [comment]
@heyitsolivia 
- Will the navigation always be displayed on a dark background (solid/photo)?
  **All pages except the home page will have that navy overlay. On the homepage, we'll want to add a gradient fade at the top just in case they ever change the photo to a suboptimal, lighter image. We will be able to use whit navigation on all pages.**
- Are there current/hover states for menu items on smaller screens? So the user can see the current page they are on highlighted in some way.
  **I've updated the tablet and mobile states to show that we'd have a line indicating which page they're on. I'm also thinking that we could use a hover effect like the 3rd example [here](http://tympanus.net/Development/CreativeLinkEffects/) for both mobile/tablet and desktop**
- Are there hover/active states for the subscribe/newsletter link? Maybe the background of the button/tab  darkens?
  **I've updated the comps to reflect changes. On desktop, let's make the background darker, on the mobile menu, let's lighten it. 
  In the desktop comps I have the bg as #0F1527 at 40% and on hover take the opacity to 100%.
  In the mobile comps I have the bg as #fff at 20% and on hover take the opacity to 40%** 
- If the user is on a subpage (for example, `/about/our-story`), will the parent group (`about`) be highlighted? For context, right now clicking on `/about` will take you to the first subpage created underneath it—per wireframes, this would be `about/overview`. `/about` wouldn't exist as a standalone page.
  **The Parent and Subpage's menu items should be highlighted, indicating the section and page that you're on.
  Example: Cornell.edu's  "About Cornell" > "Overview" page
  http://www.cornell.edu/about/index.cfm**

<img width="1098" alt="screen shot 2016-03-18 at 10 54 34 am" src="https://cloud.githubusercontent.com/assets/1167326/13881590/d64d6532-ecf7-11e5-9a50-e8a446844f79.png">

cc: @thepaleshadow

**Comment by heyitsolivia** [comment]
@alxmrtnz Thanks, that all makes sense. I like the hover animation you referenced too. Leaving a gif of it here for future reference:

![nav-link-animation](https://cloud.githubusercontent.com/assets/1198350/13882473/ec630166-ecfb-11e5-96a4-34e57efcdc46.gif)

**Comment by alxmrtnz** [comment]
@heyitsolivia Mobile nav looks great on all tested browsers.

Testing on Browserstack, IE 11 and 10 have issues:
![screen shot 2016-04-13 at 11 09 00 am](https://cloud.githubusercontent.com/assets/1167326/14498659/2ca8ad80-0169-11e6-8fc2-6686adc3a9f8.png)
![screen shot 2016-04-13 at 11 12 43 am](https://cloud.githubusercontent.com/assets/1167326/14498660/2cb18338-0169-11e6-832f-2ad2307c416c.png)

**Comment by heyitsolivia** [comment]
Add Gradient overlay 25% (cornell treatment)

**Comment by heyitsolivia** [comment]
Issue with IE 9/10: `pass-through` is not supported,  need an alternate implementation of displaying submenu dropdowns.
