### ISSUE TITLE
Set up configuration for all templates and components

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#41]
Set up custom collections for each template, and custom post types in `template.config` for components.

For reference:
**Wireframes from #2**
Invision link: https://projects.invisionapp.com/share/495Z2EAEC#/screens

**Component Inventory in #1**
![](https://cloud.githubusercontent.com/assets/1167326/13085608/0cec81a8-d4ad-11e5-9998-32353f599316.jpg)

**Comment by heyitsolivia** [comment]
Essentially, we'll need to set up each custom page on squarespace as a collection, or "blog", wherein each custom section will consist of a custom "post".

**Comment by heyitsolivia** [comment]
I've set up the following custom post types:

Hero Block (for homepage only)
Icons Block (for homepage only)
Call to Action Block
Quote Block
Media Highlights
Feature Block 
Image Highlights
Three Column Block
Text Highlights

**Comment by heyitsolivia** [comment]
Aside from a custom post type for the employee/staff block in  #13,  this is pretty much good to go.

**Comment by awarehouse** [comment]
Note: We will QA each component once development of the ticket has been completed.
