### ISSUE TITLE
Component: Icon Block

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#48]
<img width="1041" alt="screen shot 2016-04-21 at 7 35 22 pm" src="https://cloud.githubusercontent.com/assets/1198350/14727376/3dea23b8-07f8-11e6-9e0c-999e30208102.png">

**Comment by heyitsolivia** [comment]
@alxmrtnz @awarehouse This is ready for QA and content now.

**Comment by alxmrtnz** [comment]
@heyitsolivia looks good to me 👍
