### ISSUE TITLE
Component - Secondary Navigation (About Sections)

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#5]
Wireframe

![screen shot 2016-02-22 at 2 57 01 pm](https://cloud.githubusercontent.com/assets/1167326/13230742/8a1699d6-d974-11e5-80e0-02b926114e66.png)

**Comment by heyitsolivia** [comment]
**Visual design needed for the following states**
- [ ] Secondary nav on small screens
- [x] Secondary nav on large screens

**Comment by heyitsolivia** [comment]
@alxmrtnz Are there design comps for this?  Might be able to build this at the same time as the primary navigation (#4)

**Comment by alxmrtnz** [comment]
@heyitsolivia essentially it should look something like this

@thepaleshadow is going to be taking another look at it as he designs his components, so I would chat with him in case it strays from this layout.

<img width="1386" alt="screen shot 2016-03-18 at 4 27 42 pm" src="https://cloud.githubusercontent.com/assets/1167326/13891268/81bce9b4-ed26-11e5-8c6d-0e31bbf1f94b.png">

**Comment by awarehouse** [comment]
@thepaleshadow Do you expect there to be any large changes between the comp above and your final News Page comp? cc. @heyitsolivia

**Comment by thepaleshadow** [comment]
The only thing we’ve changed here is the Subscribe button at the upper right has a yellow background instead of a dark navy, to highlight it more against the dark hero photos.

**Comment by awarehouse** [comment]
cc @heyitsolivia ^^

**Comment by heyitsolivia** [comment]
@thepaleshadow Thanks. What about for mobile? I'm thinking the secondary navigation items can just stack like a vertical list on smaller screens, unless you have a better idea. cc @alxmrtnz

**Comment by heyitsolivia** [comment]
@thepaleshadow If we use the gold for the subscribe button, it looks like this. Too much contrast now?

<img width="1065" alt="screen shot 2016-03-29 at 2 17 02 pm" src="https://cloud.githubusercontent.com/assets/1198350/14118791/0fd97bbe-f5b9-11e5-95c5-5734b59253ca.png">
<img width="1070" alt="screen shot 2016-03-29 at 2 18 33 pm" src="https://cloud.githubusercontent.com/assets/1198350/14118809/28a7f012-f5b9-11e5-9587-22b7b85655a4.png">

**Comment by thepaleshadow** [comment]
Ah, my mistake! Forgot to mention we have a transparency on those to diminish the contrast—I believe it’s 40%. @heyitsolivia

**Comment by heyitsolivia** [comment]
Notes from discussion with @alxmrtnz : Responsive secondary nav could behave like a side scrolling menu: as it gets smaller, items overflow but are accessible by swiping/sliding.

**Comment by heyitsolivia** [comment]
@alxmrtnz @awarehouse Last component is done! Ready to QA and review!

**Comment by alxmrtnz** [comment]
@heyitsolivia the only thing I'd change here is to remove the transform of the underline on hover. It's a little odd having the line animate up from below on hover and break the visual container of the secondary nav.

I'd modify it so that the underline bar simply fades in but is already in its end location so that it doesn't appear to move up from below. Does that make sense?

**Comment by heyitsolivia** [comment]
Yup, I'll make that change now.
