### ISSUE TITLE
Component - Footer

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#6]
# Wireframe

*note: I think we should consider adding navigation links to this footer

![screen shot 2016-02-22 at 3 00 22 pm](https://cloud.githubusercontent.com/assets/1167326/13230846/03e6473e-d975-11e5-9f2c-342499b93bc5.png)
# Design
### Desktop

![wla-component-footer-desktop1](https://cloud.githubusercontent.com/assets/1167326/13860968/4fd4327e-ec61-11e5-959a-0387a94f9330.jpg)
### Desktop (Hover States)

![wla-component-footer-desktop2](https://cloud.githubusercontent.com/assets/1167326/13860970/51de9816-ec61-11e5-8bdb-2f7fb0213b72.jpg)
### Mobile

![wla-component-footer-mobile](https://cloud.githubusercontent.com/assets/1167326/13860976/588b605e-ec61-11e5-985b-1709c581f221.jpg)
# Acceptance Criteria
- [ ] Footer matches design comps across modern browsers (Safari, Chrome, Firefox, IE/Edge, iOS and Android)
- [ ] Empty or missing squarespace contact fields does not break the component or design (business name, title, logo, location address, contact email and contact phone number)
- [ ] Varying number of connected social accounts does not break the component or design

**Comment by heyitsolivia** [comment]
**Visual design needed for the following states**
- [x] Footer component for small screens
- [x] Footer component for large screens
- [x] Hover states for icons (optional?)

**Comment by alxmrtnz** [comment]
@heyitsolivia @thepaleshadow desktop and mobile versions of footer added

**Comment by heyitsolivia** [comment]
@alxmrtnz This looks good to me.

Couple of questions: Are we excluding phone number from the footer? And, should the logo in the footer link back to the homepage?

**Comment by alxmrtnz** [comment]
@heyitsolivia 

I forgot the phone number. Sorry about that. Also, essentially, they don't have a physical address yet. so for now it would just be the phone number and email address.

I don't think the logo in the footer needs to link to the home page to be honest. What do you think?

**Comment by heyitsolivia** [comment]
@alxmrtnz Gotcha. And I'm okay with the footer logo not linking back, I was just wondering.

**Comment by heyitsolivia** [comment]
@alxmrtnz can you identify the text color used in the footer?

**Comment by heyitsolivia** [comment]
Screenshots of the footer built out:
<img width="577" alt="screen shot 2016-03-22 at 3 21 52 pm" src="https://cloud.githubusercontent.com/assets/1198350/13964799/e8b62414-f041-11e5-8807-5e2d6edd9ca4.png">
<img width="783" alt="screen shot 2016-03-22 at 3 22 06 pm" src="https://cloud.githubusercontent.com/assets/1198350/13964806/ed7817f0-f041-11e5-890a-1b8efffc533a.png">

**Comment by awarehouse** [comment]
@alxmrtnz Did you and @heyitsolivia work out the text color?

**Comment by heyitsolivia** [comment]
@awarehouse  @alxmrtnz I extracted it from the sketch file. I'm using the hex value `#71788C` and calling it `$paleindigo`. Sound good?

**Comment by heyitsolivia** [comment]
@awarehouse

I added some acceptance criteria to the first comment, can you review and let me know if it makes sense?

Also, about the copyright line in the footer: I assume the content on the website is copyrighted, but the code for the site is open source. We should double-check and distinguish between the two.

**Comment by awarehouse** [comment]
@heyitsolivia Thanks for adding those. All, but the last one make sense to me - " Variable number of connected social accounts does not break the component or design." Is this saying that adding or subtracting variables won't break the design / component? Also, should there be a test that the Twitter / Facebook also links to the appropriate page?

**Comment by heyitsolivia** [comment]
@awarehouse Sorry, that should say _varying_ as in, any number of social media accounts. And linking to the appropriate page for each account is done automatically when you connect to each account in Squarespace, though it doesn't hurt to check.

**Comment by alxmrtnz** [comment]
@heyitsolivia looks great to me! I'm not sure how to QA on various browsers (I tried Browserstack running my local server – which has worked in the past with other projects – but I can't seem to get it working with this).

Aside from that cross-browser QA, it looks great 👍

**Comment by heyitsolivia** [comment]
@alxmrtnz awesome! we should be QAing with the live washingtonleadershipacademy.squarespace.com instead of the local server though (especially since I've found that the node squarepace server isn't 100% accurate). That should make it a bit easier to browser test :)

**Comment by alxmrtnz** [comment]
@heyitsolivia Testing with Browserstack, IE 10 and 11 are both having issues with the footer:
<img width="1414" alt="screen shot 2016-04-13 at 11 08 24 am" src="https://cloud.githubusercontent.com/assets/1167326/14498438/70c72e3e-0168-11e6-98bf-40e510498f22.png">
