### ISSUE TITLE
Component - Homepage Hero

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#7]
# Wireframe

![screen shot 2016-02-22 at 3 00 54 pm](https://cloud.githubusercontent.com/assets/1167326/13230855/14df95c2-d975-11e5-9f71-11e5f986fd38.png)
# Visual Design
## Desktop

![wla-component-homepage-hero-desktop1-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13938040/429e5930-efa0-11e5-95a3-7bb727e01dab.jpg)

![wla-component-homepage-hero-desktop2-3-21-16](https://cloud.githubusercontent.com/assets/1167326/13938041/4a1ed96e-efa0-11e5-9b45-184b6d30690b.jpg)
^ Hover style for button: Make fill white, text dark navy (the inverse of what is shown here)
## Tablet

![wla-component-homepage-hero-tablet1-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13938046/4e31b17a-efa0-11e5-8a4a-6b68135b3371.jpg)
## Mobile

![wla-component-homepage-hero-mobile1-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13938048/5271e07a-efa0-11e5-946a-de807101ca16.jpg)
# Notes
## Character Count

![character count wla-component-homepage-hero-desktop1-3-18-16](https://cloud.githubusercontent.com/assets/1167326/14118926/d222fac4-f5b9-11e5-9e5c-cd19c931a855.jpg)

**Comment by heyitsolivia** [comment]
**Visual design needed for the following states**
- [x] Hero component for small screens
- [x] Hero component for large screens
- [x] Call to action button — hover/active/focus states

**Comment by alxmrtnz** [comment]
@thepaleshadow Do you want to do a design review on this?
