### ISSUE TITLE
Group QA Fixes

### ISSUE THREAD

**Issue by heyitsolivia** [washington-leadership-academy/wla#73]
## QA Fixes

Homepage hero: background position: top center

Media Block Callout
set max width on text so it doesn’t get too long
more padding top + bottom

Text Highlights
background: accent color

Feature Block
background: jersey white

Image Gallery
background: jersey white

Team Block:
Left align instead of center align 2 column block

Content Changes:
- [x] Our Approach: Summary Line
- [x] Our Approach: Media Highlight Block
- [x] Student Life: Add another benefit about the location
- [x] Bids: Summary Block
- [x] Job Posting: Create Job Page & Link on (Now Hiring CTA Blocks)
- [x] Set up News Page (unlinked)
- [ ] Re-scrape page for Social

**Comment by heyitsolivia** [comment]
@awarehouse
Invalidate fb og cache: https://developers.facebook.com/tools/debug/sharing/batch/

**Comment by heyitsolivia** [comment]
Dev changes from today's review:
- [x] fix extra space before comma in quote attribution
- [x] increase contrast in footer text
- [x] increase font size in summary block
- [x] Call to action block: add boolean check for “open in new window”, update template
- [x] Increase contrast between CTA block and footer bg
- [x] Header images — position background images as top-center instead of center-center
- [x] Image gallery, image links open in a new window
- [x] Button block for donation/normal button
- [x] Update default sqs contact form styles
- [x] Use light version of pattern for article card placeholder

**Comment by awarehouse** [comment]
Full Meeting Notes:

Overview
- [x]  Add Partner (add an S) 
- [x] Make sure the logos link to a different tab

Our Approach
- [x] Leadership Development >> LEAD or Leadership Curriculum 
- [x] Remove the “Learn More” links from the Media Highlight 
- [x] Change CTA on page to lead to the Academics Page
- [x] Typo:  “for students in the DC and beyond”  <— needs “area”

Team
- [x] Receive new headshots and bios

Academics 
- [x] Link WLA Curriculum open to a new tab 

Enroll
- [x] CTA: Move to a different tab

News
- [x] Ask SK and NG for blog post about the new building.

Contact
- [x] Change the styling

Footer
- [x] Lighten the footer text (up the contrast)
- [x] Take out the Northeast before Washington, DC
- [x] Alert: Same School New Website!

Overall:
- [x] Update the size of the font all over the site. 
- [x] Edit the CTA’s to be lower case after the first word

User Guide
- [ ] Add PSD file for the Funder logo format
- [ ] Update FB & Twitter Profile Pic
- [ ] Include font files in the final package

cc @heyitsolivia @alxmrtnz @thepaleshadow
