### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by awarehouse** [washington-leadership-academy/wla#79]
This ticket is for all of the QA bugs / problems that Samya finds.

**Sample Page**
- [ ] Issue

**Comment by samyabehary** [comment]
Hey Arista - As discussed, here are the different pages that list the word "Enroll" or "Register." 

**HOME:**
- [x] Header Button - Register Now
- [x] Under "See How It Works" - Now **Registering** Admitted Students
- [x] Congratulations to all who were matched in the D.C. Lottery! Secure your spot now by **registering** today. CTA = Register now >> 
- [x] Footer Button - Enroll Now
