### ISSUE TITLE
Component - Inner Page Hero

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#8]
# Wireframe

![screen shot 2016-02-22 at 3 02 22 pm](https://cloud.githubusercontent.com/assets/1167326/13230897/4bfed05e-d975-11e5-9c11-8b08d7fcc304.png)
# Visual Design
## Desktop

![wla-component-inner-hero-desktop1-3-2-16](https://cloud.githubusercontent.com/assets/1167326/13939065/bac4057a-efa7-11e5-8dd7-8052d422e79c.jpg)

![wla-component-inner-hero-desktop3-3-17-16](https://cloud.githubusercontent.com/assets/1167326/13939066/bfc6470e-efa7-11e5-94fe-885360614efa.jpg)

![wla-component-inner-hero-desktop2-3-18-16](https://cloud.githubusercontent.com/assets/1167326/13939068/c3737bb0-efa7-11e5-931b-dffc4f20a40b.jpg)
## Tablet

![wla-component-inner-hero-tablet1-3-17-16](https://cloud.githubusercontent.com/assets/1167326/13939070/c92262ba-efa7-11e5-8340-314eb78718d7.jpg)
## Mobile

![wla-component-inner-hero-mobile1-3-17-16](https://cloud.githubusercontent.com/assets/1167326/13939071/cd2f76d6-efa7-11e5-9ae1-7c86bcf3f250.jpg)

**Comment by alxmrtnz** [comment]
@heyitsolivia visual design added

**Comment by heyitsolivia** [comment]
@awarehouse 
Note: Pretty much done save for one issue. Currently all pages have the page title displayed in the hero area, but according to the design comps, we want to display the parent page title on subpages.

This would either have to be set manually in Squarespace, or we would need to explore another (potentially hacky) way of getting that parent page title since it's not readily available.

**Comment by heyitsolivia** [comment]
One more thing: Need a seamless tiled fallback pattern to display in the event there is  no hero image to display. cc. @thepaleshadow

**Comment by alxmrtnz** [comment]
Testing in Browserstack:

IE 11/10 issues
- Navigation (same issue carrying over from the one I mentioned in the navigation ticket)
- Positioning of page title is a bit off 

![screen shot 2016-04-13 at 11 23 31 am](https://cloud.githubusercontent.com/assets/1167326/14498988/810d6d4c-016a-11e6-9138-2edf938f509c.png)

Medium (IE 11/10)
Looks fairly good
- Alignment issues with page title and WLA logo
  ![screen shot 2016-04-13 at 11 27 45 am](https://cloud.githubusercontent.com/assets/1167326/14499089/d585d58a-016a-11e6-804f-ca14c221aafd.png)

**Comment by heyitsolivia** [comment]
Issue with IE 9/10: `pass-through` is not supported,  need an alternate implementation of displaying submenu dropdowns.
