### ISSUE TITLE
Component - News Article Hero

### ISSUE THREAD

**Issue by alxmrtnz** [washington-leadership-academy/wla#9]
## Wireframe

![screen shot 2016-02-22 at 3 03 05 pm](https://cloud.githubusercontent.com/assets/1167326/13230921/66620056-d975-11e5-920b-679a2d58cd90.png)
## Visual Design

<img width="1440" alt="news-article-hero" src="https://cloud.githubusercontent.com/assets/14925396/14466116/74db69ce-00a3-11e6-9ecf-3714059abc48.png">
## Appears in

About > News > News article
https://invis.io/VT63IHQ67

**Comment by thepaleshadow** [comment]
Single News Article Hero @heyitsolivia @alxmrtnz  
<img width="1440" alt="news-article-hero" src="https://cloud.githubusercontent.com/assets/14925396/14466116/74db69ce-00a3-11e6-9ecf-3714059abc48.png">

**Comment by alxmrtnz** [comment]
@thepaleshadow 👍

**Comment by heyitsolivia** [comment]
@thepaleshadow @alxmrtnz This needs some changes— everywhere else on the site, that hero space is being used for the page title/subnav, which gives the user context for where you are on the site.

The news headline and news date should live in the body of the page instead.
